project:
  type: website
  output-dir: docs

website:
  title: "DT Developer Resources"
  navbar:
    left:

      - href: tabs/r.qmd
      - href: tabs/python.qmd
      - href: tabs/git.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



